FROM node:20 as build

WORKDIR /server

COPY frontend .

RUN yarn install

RUN yarn build

# Use a smaller image for serving the built app
FROM nginx:alpine

COPY --from=build /server/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]