name: tuebisearch
channels:
  - anaconda
  - conda-forge
  - https://conda.anaconda.org/conda-forge/
  - defaults
dependencies:
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - attrs=23.2.0
  - beautifulsoup4=4.12.3
  - blinker=1.8.2
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - click=8.1.7
  - colorama=0.4.6
  - dnspython=2.6.1
  - flask=3.0.3
  - flask_cors=4.0.0
  - frozenlist=1.4.1
  - idna=3.7
  - importlib-metadata=8.0.0
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - langdetect=1.0.9
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.2
  - libffi=3.4.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libsqlite=3.46.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - markupsafe=2.1.5
  - mkl=2024.1.0
  - multidict=6.0.5
  - nltk=3.8.1
  - numpy=2.0.0
  - openssl=3.3.1
  - pip=24.0
  - pymongo=4.8.0
  - python=3.12.4
  - python_abi=3.12
  - regex=2024.5.15
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - setuptools=70.3.0
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - tbb=2021.12.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tqdm=4.66.4
  - tzdata=2024a
  - werkzeug=3.0.3
  - wheel=0.43.0
  - xz=5.2.6
  - yarl=1.9.4
  - zipp=3.19.2
  - pip:
      - pyspellchecker==0.8.1
